# Generated by Django 5.0.6 on 2024-06-28 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_quantity', models.PositiveIntegerField(default=0)),
                ('st_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Purchase.itemtable')),
            ],
        ),
    ]
