# Generated by Django 5.0.6 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stocktable',
            old_name='st_quantity',
            new_name='st_purchasesStock',
        ),
        migrations.AddField(
            model_name='stocktable',
            name='st_remainingStock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktable',
            name='st_soldStock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
