# Generated by Django 5.0.6 on 2024-07-23 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktable',
            name='st_purchasesReturnStock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stocktable',
            name='st_salesReturnStock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
