# Generated by Django 5.0.6 on 2024-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricetable',
            name='pt_averagePrice',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricetable',
            name='pt_margin',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
