# Generated by Django 5.0.6 on 2024-07-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtable',
            name='item_name',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='pt_item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AlterField(
            model_name='vendortable',
            name='vendor_GST',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
