# Generated by Django 5.0.6 on 2024-08-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='companyprofileTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('company_person', models.CharField(blank=True, max_length=50, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('company_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('company_address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_gst', models.CharField(blank=True, max_length=20, null=True)),
                ('company_threshold_Stock', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
