# Generated by Django 5.0.6 on 2024-09-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_pricetable_pt_averageprice_pricetable_pt_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='pt_averagePrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='pt_sellingPrice',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
