# Generated by Django 5.0.6 on 2024-08-21 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_companyprofiletable_company_purchase_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofiletable',
            name='company_Purchase_note',
        ),
        migrations.RemoveField(
            model_name='companyprofiletable',
            name='company_Sales_note',
        ),
    ]
