# Generated by Django 5.0.6 on 2024-07-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderitemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oit_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('oit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('oit_tax_percentage', models.PositiveIntegerField(blank=True, null=True)),
                ('oit_totalprice', models.CharField(blank=True, max_length=50, null=True)),
                ('oit_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.itemtable')),
            ],
        ),
        migrations.CreateModel(
            name='purchaseorderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pot_order_number', models.CharField(max_length=20, unique=True)),
                ('pot_date', models.DateField(auto_now_add=True)),
                ('pot_items', models.ManyToManyField(through='Purchase.orderitemTable', to='Core.itemtable')),
                ('pot_vendor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Core.vendortable')),
            ],
        ),
        migrations.AddField(
            model_name='orderitemtable',
            name='oit_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Purchase.purchaseordertable'),
        ),
    ]
