# Generated by Django 5.0.6 on 2024-08-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderitemsTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oit_quantities', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='orderTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_order_number', models.CharField(max_length=20, unique=True)),
                ('ot_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='confirmPurchaseItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpit_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('cpit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cpit_tax', models.PositiveIntegerField(blank=True, null=True)),
                ('cpit_Amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cpit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable')),
            ],
        ),
        migrations.CreateModel(
            name='confirmPurchaseTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_billNum', models.CharField(max_length=20, unique=True)),
                ('cpt_date', models.DateField(auto_now_add=True)),
                ('cpt_item', models.ManyToManyField(through='Purchase.confirmPurchaseItemTable', to='Core.itemtable')),
            ],
        ),
    ]
