# Generated by Django 5.0.6 on 2024-08-16 10:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Purchase', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='confirmpurchasetable',
            name='cpt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='confirmpurchasetable',
            name='cpt_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.vendortable'),
        ),
        migrations.AddField(
            model_name='confirmpurchaseitemtable',
            name='cpit_billNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.confirmpurchasetable'),
        ),
        migrations.AddField(
            model_name='orderitemstable',
            name='oit_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='ot_items',
            field=models.ManyToManyField(through='Purchase.orderitemsTable', to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='ot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='ot_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.vendortable'),
        ),
        migrations.AddField(
            model_name='orderitemstable',
            name='oit_orderNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.ordertable'),
        ),
        migrations.AddField(
            model_name='confirmpurchasetable',
            name='cpt_poNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.ordertable'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemtable',
            name='oit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='purchaseordertable',
            name='pot_items',
            field=models.ManyToManyField(through='Purchase.purchaseorderitemTable', to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='purchaseordertable',
            name='pot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordertable',
            name='pot_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.vendortable'),
        ),
        migrations.AddField(
            model_name='purchaseorderitemtable',
            name='oit_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.purchaseordertable'),
        ),
        migrations.AddField(
            model_name='returnitemtable',
            name='rit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='returnpurchasetable',
            name='rpt_item',
            field=models.ManyToManyField(through='Purchase.returnItemTable', to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='returnpurchasetable',
            name='rpt_poNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.purchaseordertable'),
        ),
        migrations.AddField(
            model_name='returnpurchasetable',
            name='rpt_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnitemtable',
            name='rit_billNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.returnpurchasetable'),
        ),
    ]
