# Generated by Django 5.0.6 on 2024-06-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='categoryTable',
        ),
        migrations.AddField(
            model_name='itemtable',
            name='item_category',
            field=models.CharField(choices=[('Vegetables', 'Veg'), ('Fruits', 'Fru')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemtable',
            name='item_unit',
            field=models.CharField(choices=[('Kilogram', 'Kg'), ('Pieces', 'Pcs')], max_length=15),
        ),
    ]
