# Generated by Django 5.0.6 on 2024-07-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_itemtable_item_name_alter_pricetable_pt_item_and_more'),
        ('Purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtable',
            name='oit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AlterField(
            model_name='orderitemtable',
            name='oit_purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Purchase.purchaseordertable'),
        ),
        migrations.AlterField(
            model_name='purchaseordertable',
            name='pot_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.vendortable'),
        ),
    ]
