# Generated by Django 5.0.6 on 2024-06-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_delete_categorytable_itemtable_item_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitemtable',
            name='oit_unit',
        ),
        migrations.AddField(
            model_name='orderitemtable',
            name='oit_totalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
