# Generated by Django 5.0.6 on 2024-08-22 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='confirmpurchasetable',
            name='cpt_poNum',
        ),
    ]
