# Generated by Django 5.0.6 on 2024-06-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Purchase', '0003_remove_orderitemtable_oit_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemtable',
            name='oit_totalprice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordertable',
            name='pot_order_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
