# Generated by Django 5.0.6 on 2024-08-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_companyprofiletable_company_purchase_note_and_more'),
        ('Purchase', '0003_remove_confirmpurchasetable_cpt_ponum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpurchaseitemtable',
            name='cpit_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Core.itemtable'),
        ),
    ]
