# Generated by Django 5.0.6 on 2024-08-27 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_remove_companyprofiletable_company_purchase_note_and_more'),
        ('Purchase', '0005_cpt_backup_alter_confirmpurchasetable_cpt_billnum_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmpurchaseitemtable',
            name='cpit_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
            preserve_default=False,
        ),
    ]
