# Generated by Django 5.0.6 on 2024-08-24 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Damage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damagetable',
            name='dpt_timestamp',
            field=models.DateField(auto_now_add=True),
        ),
    ]
