# Generated by Django 5.0.6 on 2024-08-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_rename_user_usertable'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserTable',
            new_name='User',
        ),
    ]
