# Generated by Django 5.0.6 on 2024-07-24 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='returnsalesItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsit_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('rsit_qty', models.PositiveIntegerField(blank=True, null=True)),
                ('rsit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rsit_tax', models.PositiveIntegerField(blank=True, null=True)),
                ('rsit_offer', models.PositiveIntegerField(blank=True, null=True)),
                ('rsit_refundAmount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rsit_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable')),
            ],
        ),
        migrations.CreateModel(
            name='returnSalesTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rst_billNum', models.CharField(max_length=20, unique=True)),
                ('rst_date', models.DateTimeField(auto_now_add=True)),
                ('rst_item', models.ManyToManyField(through='Sales.returnsalesItemTable', to='Core.itemtable')),
                ('rst_poNum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.salesordertable')),
            ],
        ),
        migrations.AddField(
            model_name='returnsalesitemtable',
            name='rsit_billNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.returnsalestable'),
        ),
    ]
