# Generated by Django 5.0.6 on 2024-08-16 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Core', '0001_initial'),
        ('Sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='returnsalestable',
            name='rst_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returnsalesitemtable',
            name='rsit_billNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.returnsalestable'),
        ),
        migrations.AddField(
            model_name='salesorderitemtable',
            name='soit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='salesorderitemtable',
            name='soit_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.pricetable'),
        ),
        migrations.AddField(
            model_name='salesordertable',
            name='sot_items',
            field=models.ManyToManyField(through='Sales.salesorderItemTable', to='Core.itemtable'),
        ),
        migrations.AddField(
            model_name='salesordertable',
            name='sot_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesorderitemtable',
            name='soit_bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.salesordertable'),
        ),
        migrations.AddField(
            model_name='returnsalestable',
            name='rst_poNum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.salesordertable'),
        ),
    ]
