# Generated by Django 5.0.6 on 2024-07-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='pt_offer',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='pt_tax',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
