# Generated by Django 5.0.6 on 2024-07-04 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_alter_itemtable_item_name_alter_pricetable_pt_item_and_more'),
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderitemtable',
            name='soit_bill_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.salesordertable'),
        ),
        migrations.AlterField(
            model_name='salesorderitemtable',
            name='soit_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.itemtable'),
        ),
        migrations.AlterField(
            model_name='salesorderitemtable',
            name='soit_price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Core.pricetable'),
        ),
    ]
