# Generated by Django 5.0.6 on 2024-08-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_rst_backup_sot_backup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnsalestable',
            name='rst_poNum',
            field=models.CharField(max_length=50),
        ),
    ]
